Add core registers for Cortex M0 and M0+
ZigEmbeddedGroup/regz pull request #86
Opened 2023-02-05 22:28 UTC by jacobcpeters

This should at least partially solve issues #27 and #28. I only refactored what was already there because that should be enough for my use case. The generated output looks correct, but I can test it whenever I get some time to go back to my original project.

2023-02-10 21:55 UTC, mattnite requested changes
looking great! just some small details. This is much appreciated

2023-02-10 21:55 UTC, mattnite commented on src/svd/cmsis.zig
> +        if (cpu.properties.get("cpu.vendor_systick_config") != null)
`vendor_systick_config` needs to be evaluated, not just the null check

2023-02-10 21:55 UTC, mattnite commented on src/svd/cmsis/cortex_m0.zig
> +            db.instances.devices.get(device_id).?.properties.get("cpu.nvic_prio_bits").?,
Please handle missing prio bits by returning an error

2023-02-11 18:27 UTC, jacobcpeters commented
If `cpu.nvic_prio_bits` is missing, there should be an error earlier in the logic. However, I did make the check explicit using the same error as earlier in svd.zig:87

In the check for `cpu.vendor_systick_config`, as far as I can tell from my searches about XML, the only proper values for an `xs:boolean` are "true" and "false", both specifically lowercase, as well as "1" and "0". Any other value will return an error for the bad representation.

2023-02-12 08:15 UTC, mattnite commented
CI will dial but that’s just from zig master churn, code looks great to me, thanks!

2023-02-12 08:15 UTC, merged